export default {
  dark: {
    black: "#1B2230",
    white: "#fff",
    gray: "#788091",
    "gray-light": "#5B6270",
    "gray-lighter": "#6B7280",
    "gray-lightest": "#ECECF4",
    "gray-bg": "#FAFAFC",
    "gray-input": "#DBDDE4",
    "gray-input-disabled": "#849DAB",
    "gray-burger": "#B9BDC8",
    "border-color": "#8C94AB",
    "primary-color": "#6A38EB",
  },
  light: {
    black: "#1B2230",
    white: "#fff",
    gray: "#788091",
    "gray-light": "#5B6270",
    "gray-lighter": "#6B7280",
    "gray-lightest": "#ECECF4",
    "gray-bg": "#FAFAFC",
    "gray-input": "#DBDDE4",
    "gray-input-disabled": "#849DAB",
    "gray-burger": "#B9BDC8",
    "border-color": "#8C94AB",
    "primary-color": "#6A38EB",
  },
};
